name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Setup kubeconfig
        id: setup-kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name eks_cluster_dror
#       - name: Deploy
#         uses: scalive/github-action-eks-helm@master
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#         with:
#           args: helm upgrade  demo-flask-app --install -f charts/values.yaml charts
          
      - name: Copy kubectl config to output for helm deploy
        id: kube
        run: |
          CONFIG="$(cat ${HOME}/.kube/config)"
          CONFIG="${CONFIG//'%'/'%25'}"
          CONFIG="${CONFIG//$'\n'/'%0A'}"
          CONFIG="${CONFIG//$'\r'/'%0D'}"
          echo "::set-output name=config::$CONFIG"
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install dror ./charts
          kubeconfig: '${{ steps.kube.outputs.config }}'
#       - name: Helm install
#         uses: WyriHaximus/github-action-helm3@v2
#         with:
#           exec: helm upgrade --install dror ./charts
#           kubeconfig: '${{ secrets.KUBE_CONFIG_DATA }}'

      - name: Get URL
        id: url
        uses: koslib/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: kubectl get svc my_svc -o json | jq -r '.status.loadBalancer.ingress[0].hostname'

      - name: Print Response
        run: echo "Response was ${{ steps.url.outputs.response }}"
