name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setting kubeconfig
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        id: setcontext
        
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: 'nginx'
          namespace: 'default'
          chart: 'app'
          token: '${{ github.token }}'
          values: |
            name: foobar
          value-files: >-
            [
            "values.yaml"
            ]
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
          
#       - name: Deploy
#         uses: scalive/github-action-eks-helm@master
#         env:
#           KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#         with:
#           args: helm ls
          

          
          
#       - name: Helm Lint
#         uses: WyriHaximus/github-action-helm3@v2
#         with:
#           exec: helm lint ./charts
          
#       - name: Helm install
#         uses: WyriHaximus/github-action-helm3@v2
#         with:
#           exec: helm upgrade --install demo-flask-app ./charts
#           kubeconfig: '${{ secrets.KUBECONFIG }}'


#       - name: Print Response
#         run: echo "Response was ${{ steps.url.outputs.response }}"
