name: CI

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: azure/setup-helm@v1
        with:
          version: '3.5.2' # our current server version
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.21.0' # default is latest stable
        id: install

      # Checkout the helm repository  
      - name: Checkout texel-helm-charts
        uses: actions/checkout@v2
        with:
          repository: drorvt/grubhub-task
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: '0'
          
      # Deploy chart to GKE cluster 
      - name: Deploy rms-management-strategy chart
        run: |
          aws eks --region us-east-1 update-kubeconfig --name eks_cluster_dror
          kubectl get pods -A
          helm upgrade --install demo-flask-app ./charts

        

